### ISSUE TITLE
error inserting a font-face

### ISSUE THREAD

**Issue by jpeter06** [tomyeh/ZUSS#13]
Hello, just detected an error with quotations.

org.zkoss.zuss.ZussException: [zuss] fonts.zuss:Line 14: unclosed string literal.
Single quotation not working.

@font-face {
        font-family: 'icons';
        src: url('icons-webfont.eot');
        src: url('icons-webfont.eot?#iefix') format('embedded-opentype'),
             url('icons-webfont.woff') format('woff'),
             url('icons-webfont.ttf') format('truetype'),
             url('icons-webfont.svg#iconsMedium') format('svg');
        font-weight: normal;
        font-style: normal;
    }

```
.icons { 
    font-family: 'icons', Arial;
    font-size: 18px;
}
```

**Comment by tomyeh** [comment]
Unable to replicate the problem. Did you test with the latest version?

**Comment by jpeter06** [comment]
Ok, now I have no exception but in the output I can not fount @font-face, it disapears.

**Comment by tomyeh** [comment]
`@font-face {..}` is a definition. You have to apply it to the location you want. For example,

``` css

div {
    @font-face;
}
```

**Comment by jpeter06** [comment]
I Am using it  like here http://jsfiddle.net/xEThN/
It is not a definition, it is just like it is defined in css3, isn't it?
